### ISSUE TITLE
Mi da questo errore...

### ISSUE THREAD

**Issue by lookcatme26** [Tecnologica-Mente/Pearson_Sanoma_My_Place_eBook_Ripper#1]
![errore](https://github.com/Tecnologica-Mente/Pearson_Sanoma_My_Place_eBook_Ripper/assets/160432563/87e31ed6-c98e-4470-b7c3-efd1f1d5849a)
Ho seguito tutti i passaggi ma mi continua a dare questo errore... 403 Forbidden... possibili rimedi?

**Comment by Tecnologica-Mente** [comment]
Si, hanno bloccato lo script. Utilizza lo script nella repository "PDFGrabber_Launcher" (https://github.com/Tecnologica-Mente/PDFGrabber_Launcher), è in grado di scaricare PDF dalla maggior parte delle piattaforme online disponibili.

**Comment by lookcatme26** [comment]
Grazie funziona :)

**Comment by Tecnologica-Mente** [comment]
Ottimo! :-)
